### ISSUE TITLE
How to clear Playerlist and re-create with new set of Players

### ISSUE THREAD

**Issue by Kenworld** [brkckr/FirstEleven#1]
Is there a way to clear the player list and add a different team players. For a example i have Home Team and Away team. how do i switch between teams

**Comment by brkckr** [comment]
Hi,
As far as I understand from what you wrote above, you just want to clear Field and create new FirstEleven for the other team.

` cleanContainer(); `// clears all the child elements of mother container.
 
 After cleaning the container, you only see, there is a field. Then you must create new FirstEleven.
 `createFirstEleven(new FirstEleven("Your New Team Name", "New Coach Name", "New Tactic Name(ex : 4-1-4-1)", newPlayerList));`
 You should change the 4 parameters of constructor of FirstEleven object while creating a new one.

I saw your e-mail, I think it would be better if I reply here, maybe it will be useful for someone else. Please let me know if this helps.
